version: '3'
services:
  healthcar-crm:
    container_name: healthcar-back
    build:
      context: .
      dockerfile: Dockerfile
    image: healthcar
    ports:
      - 8080:8080
    networks:
      - bridge-network
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge