version: '3'
services:
  healthcar-rmi:
    container_name: healthcar-back
    build:
      context: .
      dockerfile: Dockerfile
    image: healthcar
    ports:
      - 8080:8080
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge