server:
  port: 8080
  shutdown: graceful

spring:
  banner:
    location: banner.txt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: /database/liquibase/master.xml
    url: jdbc:postgresql://postgres:5432/postgres
    user: root
    password: root
    driver-class-name: org.postgresql.Driver
  lifecycle:
    timeout-per-shutdown-phase: 1m

springdoc:
  api-docs:
    path: /api-doc

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - liquibase
          - metrics
          - shutdown
  server:
    port: 8081

